### ISSUE TITLE
babel-plugin-transform-object-rest-spread dependency, not sure if this is required

### ISSUE THREAD

**Issue by chrisirhc** [btford/react-palm#34]
https://github.com/btford/react-palm/blob/1844cec4fa2547bd8137ae1bec8bb39b067b75eb/package.json#L26

Saw this in the dependencies but I didn't see it being used anywhere. Perhaps it should be in `devDependencies`?

**Comment by btford** [comment]
Removed this and a handful of other deps when moving to Babel 7: 38832a16155dadd3d93e19a2b5e0f54488edb7bf
